### ISSUE TITLE
Stuck on "Starting Watchtower ......................... OK"

### ISSUE THREAD

**Issue by BlueskyFR** [Jigsaw-Code/outline-server#27]
Sorry for duplicate but I really need help with this, and exporting public ip adresse doesn't change anything.

Thanks for your help.

**Comment by timmmmmmmmm** [comment]
You'll get this message when you don't have all your ports open on your server. I got stuck on it on Aliyun too, untill I added a security rule to open them all. Outline chooses a randomized port, I guess after setup you can close all unneeded ports again except the configured one.

**Comment by thomamvt** [comment]
What i did was "iptables -A INPUT -p tcp -m multiport --dports 1024:65535 -j ACCEPT" on a debian server, before starting the watch tower script.
I was able to complete the installation after that, but still no luck with the server software "outline manager" it fails to connect to API on the specific port.

**Comment by 4044ever** [comment]
@thomamvt 
I tried it on my Raspberry: 

`iptables -A INPUT -p tcp -m multiport --dports 1024:65535 -j ACCEPT`

All routerports 1080 - 65535 are open.

It hangs here after doing the bash -x:

`+ curl --cacert /root/.shadowbox/persisted-state/shadowbox-selfsigned.crt -s https://66.222.164.21:26392/vayH6RGFxCuU_PbLQyHHYA/access-keys`

What might the problem be?

**Comment by 4044ever** [comment]
Slightly different here:

```
user@raspberrypi:/home/pi# sudo wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | bash
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Starting Shadowbox .......................... OK
> Starting Watchtower ......................... OK
> Waiting for Outline server to be healthy ....  
```

Hanging at "Waiting for Outline server to be healthy"

What does it mean?

**Comment by thomamvt** [comment]
I'm not an expert, but i think its means, some ports are not open.

**Comment by thomamvt** [comment]
@4044ever I've no idea why it hangs, you can try the below command.

iptables -A INPUT -p tcp --dport 1024:65535 -j ACCEPT
iptables -A INPUT -p udp --dport 1024:65535 -j ACCEPT

**Comment by 4044ever** [comment]
@thomamvt 
Same problem. When I do a bash -x now it looks like that:

`+ curl --insecure -s https://localhost:25629/zWCZyr1pleXCQMEpp8AeQA/access-keys`

For some reasons it changed from the external IP to 'localhost'

**Comment by thomamvt** [comment]
I've no idea why its changing from external to localhost. I had no issues
on debian 64 bit on amazon EC2.

Thanks & Regards...

Thomas Mathew
email-thomamvt@gmail.com

*Ph: +1 (732) 305-0138*

**Comment by fortuna** [comment]
@thomamvt  It's using `localhost` in order to check the health of the service without hitting external firewalls.

The script has been updated. Please try again

**Comment by fortuna** [comment]
@4044ever It was hanging there waiting the service to be ready, but the check was likely being blocked by a firewall. We've updated the script to better communicate that.

**Comment by fortuna** [comment]
The original issue was likely due to a firewall. https://github.com/Jigsaw-Code/outline-server/pull/38 should have clarified what's going on in the installation and provide the information needed for you to unblock the ports.

I'm marking this as closed. We can reopen as a different issue if needed.

**Comment by 4044ever** [comment]
I still get stuck at the same spot. With bash -x

`+ curl --insecure -s https://localhost:29639/W4YolAMs4ArLXXs3oUU1ig/access-keys`

With bash only:
`> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Starting Shadowbox .......................... OK
> Starting Watchtower ......................... OK
> Waiting for Outline server to be healthy ....`

Just in case it makes a different, it's a Raspberry Pi3 and the OS is Raspian. It runs already ShadowsocksR and V2Ray successfully for a few week.

The Raspi is directly LAN connected to a router. All ports (1080-6635) are UDP/TCP forwarded/open. 
Is there any other Firewall somewhere? It seems strange because other ports I opened for SSR and V2Ray work.

**Comment by fortuna** [comment]
@404ever: Things to try when the script gets stuck there::
- Run `docker logs shadowbox`to get the shadowbox logs
- Run `curl --insecure -s -v https://localhost:29639/<secret>/access-keys` with the `-v` for verbose output

It seems the server never goes up, or the port was blocked somehow.

**Comment by fortuna** [comment]
@ex7r3me did you have to change anything in the install script other than the image name to make it work?

If not, then you can specify your image with `SB_IMAGE`. Example:

```
{ export SB_IMAGE=ex7r3me/shadowbox; sudo wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | bash; }
```

**Comment by puppeteer701** [comment]
@fortuna I tried your suggestion, but still, it gets stuck on 

```
Waiting for Outline server to be healthy ....
```

I am trying to use Raspberry pie 3 and also trying ong Raspberry pi Zero W.

**Comment by PekopT** [comment]
FYI: check if there is `curl` installed in OS.

**Comment by denny70** [comment]
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Setting PUBLIC_HOSTNAME to external IP ...... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate .................. OK
> Generating SHA-256 certificate fingerprint .. OK
> Writing config .............................. OK
> Starting Shadowbox .......................... OK
> Starting Watchtower ......................... FAILED
> The container name "watchtower" is already in use by another container. This may happen when running this script multiple times. Would you like to replace this container? If you answer no, we will proceed with the remainder of the installation. [Y/n] y
> Removing watchtower container ............... OK
> Restarting watchtower ....................... OK
> Waiting for Outline server to be healthy ....

==> stuck here,, you can use " docker logs shadowbox" to see what happened
ex: here is mine

 docker logs shadowbox
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.47/containers/shadowbox/json": dial unix /var/run/docker.sock: connect: permission denied

--> add Docker into no need sudo 

 sudo gpasswd -a $USER docker
Adding user ubuntu to group docker

--> fix issue, but maybe you will see you set port in Outline but the port was used.
enjoy
