### ISSUE TITLE
Outline-server won't starting

### ISSUE THREAD

**Issue by empty-field** [Jigsaw-Code/outline-server#341]
Old installation of Outline in some time ago stopped working, and new installation on two different VPS also not working. Instead it loads VPS CPU about 60%, flooding with errors to "shadowbox" container's console, and same lines in container's log.
Pretty sorry but i don't know how to attach file here, here is part of log:
```
18-12-07T09:25:41.648Z 9 main.js:109] === Config ===\n","stream":"stdout","time":"2018-12-07T09:25:41.649844994Z"}
{"log":"D2018-12-07T09:25:41.650Z 9 main.js:110] SB_PUBLIC_IP: 5.61.x.x\n","stream":"stdout","time":"2018-12-07T09:25:41.650784392Z"}
{"log":"D2018-12-07T09:25:41.650Z 9 main.js:111] SB_METRICS_URL: https://metrics-prod.uproxy.org\n","stream":"stdout","time":"2018-12-07T09:25:41.651045368Z"}
{"log":"D2018-12-07T09:25:41.651Z 9 main.js:112] ==============\n","stream":"stdout","time":"2018-12-07T09:25:41.651244795Z"}
{"log":"I2018-12-07T09:25:41.652Z 9 main.js:121] Starting...\n","stream":"stdout","time":"2018-12-07T09:25:41.652413694Z"}
{"log":"I2018-12-07T09:25:41.659Z 9 main.js:128] Prometheus is at localhost:9090\n","stream":"stdout","time":"2018-12-07T09:25:41.65923914Z"}
{"log":"I2018-12-07T09:25:41.659Z 9 main.js:129] Node metrics is at localhost:9091\n","stream":"stdout","time":"2018-12-07T09:25:41.659474777Z"}
{"log":"I2018-12-07T09:25:41.660Z 9 main.js:143] outline-ss-server metrics is at localhost:9092\n","stream":"stdout","time":"2018-12-07T09:25:41.66018941Z"}
{"log":"I2018-12-07T09:25:41.761Z 9 main.js:185] Manager listening at https://[::]:57329/7aUmU9GBUitc308omS6_UA\n","stream":"stdout","time":"2018-12-07T09:25:41.762147004Z"}
{"log":"I2018-12-07T09:25:41.780Z 20 server.go:224] Metrics on http://localhost:9092/metrics\n","stream":"stderr","time":"2018-12-07T09:25:41.781760255Z"}
{"log":"I2018-12-07T09:25:41.782Z 20 server.go:230] Using IP-Country database at /var/lib/libmaxminddb/GeoLite2-Country.mmdb\n","stream":"stderr","time":"2018-12-07T09:25:41.782941064Z"}
{"log":"I2018-12-07T09:25:41.785Z 20 server.go:75] Listening TCP and UDP on port 48916\n","stream":"stderr","time":"2018-12-07T09:25:41.785187671Z"}
{"log":"I2018-12-07T09:25:41.785Z 20 server.go:149] Loaded 1 access keys\n","stream":"stderr","time":"2018-12-07T09:25:41.785498514Z"}
{"log":"C2018-12-07T09:25:41.790Z 20 server.go:222] listen tcp 66.96.162.92:9092: bind: cannot assign requested address\n","stream":"stderr","time":"2018-12-07T09:25:41.790738019Z"}
{"log":"I2018-12-07T09:25:41.794Z 9 outline_shadowsocks_server.js:84] outline-ss-server has exited with error. Code: 1, Signal: null\n","stream":"stdout","time":"2018-12-07T09:25:41.794424268Z"}
{"log":"I2018-12-07T09:25:41.795Z 9 outline_shadowsocks_server.js:85] Restarting\n","stream":"stdout","time":"2018-12-07T09:25:41.795507174Z"}
{"log":"I2018-12-07T09:25:41.805Z 31 server.go:224] Metrics on http://localhost:9092/metrics\n","stream":"stderr","time":"2018-12-07T09:25:41.805783737Z"}
{"log":"I2018-12-07T09:25:41.805Z 31 server.go:230] Using IP-Country database at /var/lib/libmaxminddb/GeoLite2-Country.mmdb\n","stream":"stderr","time":"2018-12-07T09:25:41.806084165Z"}
{"log":"I2018-12-07T09:25:41.806Z 31 server.go:75] Listening TCP and UDP on port 48916\n","stream":"stderr","time":"2018-12-07T09:25:41.806735646Z"}
{"log":"I2018-12-07T09:25:41.813Z 31 server.go:149] Loaded 1 access keys\n","stream":"stderr","time":"2018-12-07T09:25:41.813370499Z"}
{"log":"C2018-12-07T09:25:41.816Z 31 server.go:222] listen tcp 66.96.162.92:9092: bind: cannot assign requested address\n","stream":"stderr","time":"2018-12-07T09:25:41.816833934Z"}
{"log":"I2018-12-07T09:25:41.817Z 9 outline_shadowsocks_server.js:84] outline-ss-server has exited with error. Code: 1, Signal: null\n","stream":"stdout","time":"2018-12-07T09:25:41.818004523Z"}
{"log":"I2018-12-07T09:25:41.818Z 9 outline_shadowsocks_server.js:85] Restarting\n","stream":"stdout","time":"2018-12-07T09:25:41.818207575Z"}
{"log":"level=info ts=2018-12-07T09:25:41.825727293Z caller=main.go:238 msg=\"Starting Prometheus\" version=\"(version=2.4.3, branch=HEAD, revision=167a4b4e73a8eca8df648d2d2043e21bdb9a7449)\"\n","stream":"stderr","time":"2018-12-07T09:25:41.825969762Z"}
{"log":"level=info ts=2018-12-07T09:25:41.826102937Z caller=main.go:239 build_context=\"(go=go1.11.1, user=root@1e42b46043e9, date=20181004-08:42:02)\"\n","stream":"stderr","time":"2018-12-07T09:25:41.826233933Z"}
{"log":"level=info ts=2018-12-07T09:25:41.826348373Z caller=main.go:240 host_details=\"(Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 server.domain.com (none))\"\n","stream":"stderr","time":"2018-12-07T09:25:41.826485853Z"}
{"log":"level=info ts=2018-12-07T09:25:41.826610832Z caller=main.go:241 fd_limits=\"(soft=32768, hard=32768)\"\n","stream":"stderr","time":"2018-12-07T09:25:41.826740742Z"}
{"log":"level=info ts=2018-12-07T09:25:41.826847349Z caller=main.go:242 vm_limits=\"(soft=unlimited, hard=unlimited)\"\n","stream":"stderr","time":"2018-12-07T09:25:41.826979987Z"}
{"log":"level=info ts=2018-12-07T09:25:41.827765695Z caller=main.go:554 msg=\"Starting TSDB ...\"\n","stream":"stderr","time":"2018-12-07T09:25:41.831475749Z"}
{"log":"I2018-12-07T09:25:41.835Z 40 server.go:224] Metrics on http://localhost:9092/metrics\n","stream":"stderr","time":"2018-12-07T09:25:41.835801385Z"}
{"log":"I2018-12-07T09:25:41.835Z 40 server.go:230] Using IP-Country database at /var/lib/libmaxminddb/GeoLite2-Country.mmdb\n","stream":"stderr","time":"2018-12-07T09:25:41.836074892Z"}
{"log":"I2018-12-07T09:25:41.838Z 40 server.go:75] Listening TCP and UDP on port 48916\n","stream":"stderr","time":"2018-12-07T09:25:41.839097054Z"}
{"log":"I2018-12-07T09:25:41.839Z 40 server.go:149] Loaded 1 access keys\n","stream":"stderr","time":"2018-12-07T09:25:41.839397855Z"}
{"log":"level=info ts=2018-12-07T09:25:41.845197566Z caller=web.go:397 component=web msg=\"Start listening for connections\" address=localhost:9090\n","stream":"stderr","time":"2018-12-07T09:25:41.84540679Z"}
{"log":"level=info ts=2018-12-07T09:25:41.846741149Z caller=main.go:564 msg=\"TSDB started\"\n","stream":"stderr","time":"2018-12-07T09:25:41.846908734Z"}
{"log":"level=info ts=2018-12-07T09:25:41.847024509Z caller=main.go:624 msg=\"Loading configuration file\" filename=/opt/outline/persisted-state/prometheus/config.yml\n","stream":"stderr","time":"2018-12-07T09:25:41.847164371Z"}
{"log":"level=info ts=2018-12-07T09:25:41.848441738Z caller=main.go:650 msg=\"Completed loading of configuration file\" filename=/opt/outline/persisted-state/prometheus/config.yml\n","stream":"stderr","time":"2018-12-07T09:25:41.848614905Z"}
{"log":"level=info ts=2018-12-07T09:25:41.848724125Z caller=main.go:523 msg=\"Server is ready to receive web requests.\"\n","stream":"stderr","time":"2018-12-07T09:25:41.848870253Z"}
{"log":"C2018-12-07T09:25:41.859Z 40 server.go:222] listen tcp 66.96.162.92:9092: bind: cannot assign requested address\n","stream":"stderr","time":"2018-12-07T09:25:41.860052615Z"}
{"log":"I2018-12-07T09:25:41.860Z 9 outline_shadowsocks_server.js:84] outline-ss-server has exited with error. Code: 1, Signal: null\n","stream":"stdout","time":"2018-12-07T09:25:41.86087516Z"}
{"log":"I2018-12-07T09:25:41.860Z 9 outline_shadowsocks_server.js:85] Restarting\n","stream":"stdout","time":"2018-12-07T09:25:41.861072313Z"}
{"log":"level=info ts=2018-12-07T09:25:41.862176266Z caller=main.go:423 msg=\"Stopping scrape discovery manager...\"\n","stream":"stderr","time":"2018-12-07T09:25:41.865599232Z"}
{"log":"level=info ts=2018-12-07T09:25:41.862226278Z caller=main.go:437 msg=\"Stopping notify discovery manager...\"\n","stream":"stderr","time":"2018-12-07T09:25:41.865636359Z"}
{"log":"level=info ts=2018-12-07T09:25:41.862241029Z caller=main.go:459 msg=\"Stopping scrape manager...\"\n","stream":"stderr","time":"2018-12-07T09:25:41.865642738Z"}
{"log":"level=info ts=2018-12-07T09:25:41.862267907Z caller=main.go:419 msg=\"Scrape discovery manager stopped\"\n","stream":"stderr","time":"2018-12-07T09:25:41.865648546Z"}
{"log":"level=info ts=2018-12-07T09:25:41.862293669Z caller=main.go:433 msg=\"Notify discovery manager stopped\"\n","stream":"stderr","time":"2018-12-07T09:25:41.865654013Z"}
{"log":"level=info ts=2018-12-07T09:25:41.86233124Z caller=manager.go:638 component=\"rule manager\" msg=\"Stopping rule manager...\"\n","stream":"stderr","time":"2018-12-07T09:25:41.865659675Z"}
{"log":"level=info ts=2018-12-07T09:25:41.862346912Z caller=manager.go:644 component=\"rule manager\" msg=\"Rule manager stopped\"\n","stream":"stderr","time":"2018-12-07T09:25:41.865665229Z"}
{"log":"level=info ts=2018-12-07T09:25:41.862584279Z caller=notifier.go:512 component=notifier msg=\"Stopping notification manager...\"\n","stream":"stderr","time":"2018-12-07T09:25:41.865683129Z"}
{"log":"level=info ts=2018-12-07T09:25:41.862608083Z caller=main.go:608 msg=\"Notifier manager stopped\"\n","stream":"stderr","time":"2018-12-07T09:25:41.865703842Z"}
{"log":"level=info ts=2018-12-07T09:25:41.862625306Z caller=main.go:453 msg=\"Scrape manager stopped\"\n","stream":"stderr","time":"2018-12-07T09:25:41.865709388Z"}
{"log":"level=error ts=2018-12-07T09:25:41.862644593Z caller=main.go:617 err=\"error starting web server: listen tcp 66.96.162.92:9090: bind: cannot assign requested address\"\n","stream":"stderr","time":"2018-12-07T09:25:41.865714952Z"}
{"log":"I2018-12-07T09:25:41.866Z 9 prometheus_scraper.js:70] prometheus has exited with error. Code: 1, Signal: null\n","stream":"stdout","time":"2018-12-07T09:25:41.866594123Z"}
{"log":"I2018-12-07T09:25:41.870Z 48 server.go:224] Metrics on http://localhost:9092/metrics\n","stream":"stderr","time":"2018-12-07T09:25:41.870406236Z"}
{"log":"I2018-12-07T09:25:41.870Z 48 server.go:230] Using IP-Country database at /var/lib/libmaxminddb/GeoLite2-Country.mmdb\n","stream":"stderr","time":"2018-12-07T09:25:41.870695197Z"}
{"log":"I2018-12-07T09:25:41.871Z 48 server.go:75] Listening TCP and UDP on port 48916\n","stream":"stderr","time":"2018-12-07T09:25:41.871431876Z"}
{"log":"I2018-12-07T09:25:41.871Z 48 server.go:149] Loaded 1 access keys\n","stream":"stderr","time":"2018-12-07T09:25:41.871674369Z"}
{"log":"C2018-12-07T09:25:41.873Z 48 server.go:222] listen tcp 66.96.162.92:9092: bind: cannot assign requested address\n","stream":"stderr","time":"2018-12-07T09:25:41.873740013Z"}
{"log":"I2018-12-07T09:25:41.874Z 9 outline_shadowsocks_server.js:84] outline-ss-server has exited with error. Code: 1, Signal: null\n","stream":"stdout","time":"2018-12-07T09:25:41.874912951Z"}
{"log":"I2018-12-07T09:25:41.875Z 9 outline_shadowsocks_server.js:85] Restarting\n","stream":"stdout","time":"2018-12-07T09:25:41.875124444Z"}
{"log":"I2018-12-07T09:25:41.880Z 54 server.go:224] Metrics on http://localhost:9092/metrics\n","stream":"stderr","time":"2018-12-07T09:25:41.881132861Z"}
{"log":"I2018-12-07T09:25:41.881Z 54 server.go:230] Using IP-Country database at /var/lib/libmaxminddb/GeoLite2-Country.mmdb\n","stream":"stderr","time":"2018-12-07T09:25:41.881459628Z"}
{"log":"I2018-12-07T09:25:41.881Z 54 server.go:75] Listening TCP and UDP on port 48916\n","stream":"stderr","time":"2018-12-07T09:25:41.882121598Z"}
{"log":"I2018-12-07T09:25:41.882Z 54 server.go:149] Loaded 1 access keys\n","stream":"stderr","time":"2018-12-07T09:25:41.882389743Z"}
{"log":"C2018-12-07T09:25:41.884Z 54 server.go:222] listen tcp 66.96.162.92:9092: bind: cannot assign requested address\n","stream":"stderr","time":"2018-12-07T09:25:41.884616982Z"}
{"log":"I2018-12-07T09:25:41.885Z 9 outline_shadowsocks_server.js:84] outline-ss-server has exited with error. Code: 1, Signal: null\n","stream":"stdout","time":"2018-12-07T09:25:41.885863912Z"}
{"log":"I2018-12-07T09:25:41.885Z 9 outline_shadowsocks_server.js:85] Restarting\n","stream":"stdout","time":"2018-12-07T09:25:41.886084857Z"}
{"log":"I2018-12-07T09:25:41.891Z 60 server.go:224] Metrics on http://localhost:9092/metrics\n","stream":"stderr","time":"2018-12-07T09:25:41.892066491Z"}
{"log":"I2018-12-07T09:25:41.892Z 60 server.go:230] Using IP-Country database at /var/lib/libmaxminddb/GeoLite2-Country.mmdb\n","stream":"stderr","time":"2018-12-07T09:25:41.892398958Z"}
{"log":"I2018-12-07T09:25:41.892Z 60 server.go:75] Listening TCP and UDP on port 48916\n","stream":"stderr","time":"2018-12-07T09:25:41.893094008Z"}
{"log":"I2018-12-07T09:25:41.893Z 60 server.go:149] Loaded 1 access keys\n","stream":"stderr","time":"2018-12-07T09:25:41.893339407Z"}
{"log":"C2018-12-07T09:25:41.902Z 60 server.go:222] listen tcp 66.96.162.92:9092: bind: cannot assign requested address\n","stream":"stderr","time":"2018-12-07T09:25:41.902847701Z"}
{"log":"I2018-12-07T09:25:41.904Z 9 outline_shadowsocks_server.js:84] outline-ss-server has exited with error. Code: 1, Signal: null\n","stream":"stdout","time":"2018-12-07T09:25:41.904495557Z"}
{"log":"I2018-12-07T09:25:41.904Z 9 outline_shadowsocks_server.js:85] Restarting\n","stream":"stdout","time":"2018-12-07T09:25:41.904765071Z"}
{"log":"I2018-12-07T09:25:41.910Z 66 server.go:224] Metrics on http://localhost:9092/metrics\n","stream":"stderr","time":"2018-12-07T09:25:41.910871203Z"}
{"log":"I2018-12-07T09:25:41.911Z 66 server.go:230] Using IP-Country database at /var/lib/libmaxminddb/GeoLite2-Country.mmdb\n","stream":"stderr","time":"2018-12-07T09:25:41.91118846Z"}
{"log":"I2018-12-07T09:25:41.911Z 66 server.go:75] Listening TCP and UDP on port 48916\n","stream":"stderr","time":"2018-12-07T09:25:41.911925638Z"}
{"log":"I2018-12-07T09:25:41.912Z 66 server.go:149] Loaded 1 access keys\n","stream":"stderr","time":"2018-12-07T09:25:41.91217304Z"}
{"log":"C2018-12-07T09:25:41.950Z 66 server.go:222] listen tcp 66.96.162.92:9092: bind: cannot assign requested address\n","stream":"stderr","time":"2018-12-07T09:25:41.951433258Z"}
{"log":"I2018-12-07T09:25:41.952Z 9 outline_shadowsocks_server.js:84] outline-ss-server has exited with error. Code: 1, Signal: null\n","stream":"stdout","time":"2018-12-07T09:25:41.952777305Z"}
{"log":"I2018-12-07T09:25:41.952Z 9 outline_shadowsocks_server.js:85] Restarting\n","stream":"stdout","time":"2018-12-07T09:25:41.953002869Z"}
```
and so until filling of whole HDD.
How can I trace the problem to override it (or help with overriding)?
Server - KVM, Debian 9.6, Docker installed with Outline's installation script. Old server was on XEN, had same problem.

**Comment by trevj** [comment]
@empty-field Thanks for the report. Sorry you're having problems with Outline.

@fortuna Any ideas? The lines that stand out for me:
```
{"log":"C2018-12-07T09:25:41.790Z 20 server.go:222] listen tcp x.x.x.x:9092: bind: cannot assign requested address\n","stream":"stderr","time":"2018-12-07T09:25:41.790738019Z"}
{"log":"I2018-12-07T09:25:41.794Z 9 outline_shadowsocks_server.js:84] outline-ss-server has exited with error. Code: 1, Signal: null\n","stream":"stdout","time":"2018-12-07T09:25:41.794424268Z"}
```

**Comment by fortuna** [comment]
@empty-field  It seems you have something already running on your port 9092. You can identify what's taking that port with
```
lsof -i tcp -s tcp:listen
```

Would you mind trying that and report back?

This shouldn't be happening though, since we skip used ports when allocating the metrics port:
https://github.com/Jigsaw-Code/outline-server/blob/d3a8fd08135451205115dd644d28ca7f678418e0/src/shadowbox/server/main.ts#L149

**Comment by empty-field** [comment]
@fortuna Sure.
```
root@server:/home/wr# lsof -i -s tcp:listen
COMMAND   PID        USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
sshd      370        root    3u  IPv4  11923      0t0  TCP *:22022 (LISTEN)
sshd      370        root    4u  IPv6  11934      0t0  TCP *:22022 (LISTEN)
exim4     711 Debian-exim    3u  IPv4  12475      0t0  TCP localhost.localdomain:smtp (LISTEN)
exim4     711 Debian-exim    4u  IPv6  12477      0t0  TCP [::1]:smtp (LISTEN)
openvpn 13244      nobody    6u  IPv4 783892      0t0  TCP *:https (LISTEN)
node    17521        root   12u  IPv4 808061      0t0  TCP localhost.localdomain:9091 (LISTEN)
node    17521        root   15u  IPv6 808205      0t0  TCP *:37861 (LISTEN)
```
Also, IP in logs (66.96.162.92) is definitely not IP of my VPS.

**Comment by fortuna** [comment]
For some reason the Go server is trying to listen on the 66.96... IP address for the metrics HTTP server, even though we pass `localhost:9092` (it's shows in the logs). That IP doesn't even match the 5.61.... IP automatically detected for the server.

There's no port 9092 being used, that's why the port tests don't fail. It's failing to listen because the IP is somehow bogus. It's unclear to me why that's happening.

**Comment by rtsp** [comment]
Similar problem to me.

Most interesting part of these logs is the first line (cannot assign requested address). An IP address shown is not an IP of this outline server (`outline.mydomain.com`), instead, it's an IP of root domain of this outline server (`mydomain.com`).

I've checked my config and confirmed that no configuration pointed to `mydomain.com`. May be this is a bug while parsing hostname before resolving to IP address use for listening?

```
{"log":"C2018-12-12T05:05:28.558Z 25197 server.go:222] listen tcp 103.253.x.x:9092: bind: cannot assign requested address\n","stream":"stderr","time":"2018-12-12T05:05:28.558196863Z"}
{"log":"I2018-12-12T05:05:28.558Z 9 outline_shadowsocks_server.js:84] outline-ss-server has exited with error. Code: 1, Signal: null\n","stream":"stdout","time":"2018-12-12T05:05:28.559033043Z"}
{"log":"I2018-12-12T05:05:28.559Z 9 outline_shadowsocks_server.js:85] Restarting\n","stream":"stdout","time":"2018-12-12T05:05:28.559319398Z"}
{"log":"I2018-12-12T05:05:28.563Z 25206 server.go:224] Metrics on http://localhost:9092/metrics\n","stream":"stderr","time":"2018-12-12T05:05:28.563674085Z"}
{"log":"I2018-12-12T05:05:28.564Z 25206 server.go:230] Using IP-Country database at /var/lib/libmaxminddb/GeoLite2-Country.mmdb\n","stream":"stderr","time":"2018-12-12T05:05:28.564235034Z"}
{"log":"I2018-12-12T05:05:28.564Z 25206 server.go:75] Listening TCP and UDP on port 34623\n","stream":"stderr","time":"2018-12-12T05:05:28.564846142Z"}
{"log":"I2018-12-12T05:05:28.564Z 25206 server.go:75] Listening TCP and UDP on port 64413\n","stream":"stderr","time":"2018-12-12T05:05:28.565069506Z"}
{"log":"I2018-12-12T05:05:28.564Z 25206 server.go:75] Listening TCP and UDP on port 2507\n","stream":"stderr","time":"2018-12-12T05:05:28.565134663Z"}
{"log":"I2018-12-12T05:05:28.565Z 25206 server.go:75] Listening TCP and UDP on port 29701\n","stream":"stderr","time":"2018-12-12T05:05:28.565313511Z"}
{"log":"I2018-12-12T05:05:28.565Z 25206 server.go:149] Loaded 4 access keys\n","stream":"stderr","time":"2018-12-12T05:05:28.565537866Z"}
```

**Comment by empty-field** [comment]
Oh yeah. I uninstalled shadowbox and watchtower containers, did docker system prune -a, edited hostname of VPS from default "server.domain.com" to just "server" (hosts file too), and installed outline again with script from outline manager. Now it works for me, but can be critical for someone with proper subdomain.
@rtsp Thanks!

**Comment by empty-field** [comment]
@rtsp
In default hosts file on my server domain name "server.domain.com" was directed to 127.0.0.1. Shouldn't outline-ss-server use local hosts file instead of public DNS info in that case?

**Comment by Iv3x** [comment]
got he same problem :-(

**Comment by MaybeGoogle** [comment]
Same thing on a new install of Outline on Ubuntu 16.04.5.

**Comment by rtsp** [comment]
I can confirm that running `curl -4s https://ipinfo.io/ip` on outline server return correct public IP address.

In case that installer script getting the wrong IP during installation, is it possible to edit these config after installed?

**Comment by fortuna** [comment]
@rtsp it possible, but a bit involved:

1) Save the environment of the running container:
```
sudo docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' shadowbox | grep SB_ > /opt/outline/docker.env
```
2) Edit `SB_PUBLIC_IP` on `docker.env`

3) Destroy and relaunch the docker container:
```
sudo docker stop shadowbox && docker rm shadowbox && docker run -d --name shadowbox --restart=always --net=host -v /opt/outline/persisted-state:/opt/outline/persisted-state --env-file=/opt/outline/docker.env quay.io/outline/shadowbox:stable 2>&1 >/dev/null
```

**Comment by fortuna** [comment]
One thing to try that may give us more information is to run prometheus manually:
```
sudo docker exec -it shadowbox /root/shadowbox/bin/prometheus --config.file /opt/outline/persisted-state/prometheus/config.yml --storage.tsdb.retention 31d --storage.tsdb.path /opt/outline/persisted-state/prometheus/data --web.listen-address localhost:9090 --log.level debug
```

Do you get the same error?

**Comment by MaybeGoogle** [comment]
```
~# sudo docker exec -it shadowbox /root/shadowbox/bin/prometheus --config.file /opt/outline/persisted-state/prometheus/config.yml --storage.tsdb.retention 31d --storage.tsdb.path /opt/outline/persisted-state/prometheus/data --web.listen-address localhost:9090 --log.level debug
level=info ts=2018-12-17T16:50:23.728840403Z caller=main.go:238 msg="Starting Prometheus" version="(version=2.4.3, branch=HEAD, revision=167a4b4e73a8eca8df648d2d2043e21bdb9a7449)"
level=info ts=2018-12-17T16:50:23.730891281Z caller=main.go:239 build_context="(go=go1.11.1, user=root@1e42b46043e9, date=20181004-08:42:02)"
level=info ts=2018-12-17T16:50:23.730946547Z caller=main.go:240 host_details="(Linux 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 OutlineChina.com (none))"
level=info ts=2018-12-17T16:50:23.730991255Z caller=main.go:241 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2018-12-17T16:50:23.731028835Z caller=main.go:242 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2018-12-17T16:50:23.731770269Z caller=main.go:554 msg="Starting TSDB ..."
level=info ts=2018-12-17T16:50:23.763464896Z caller=web.go:397 component=web msg="Start listening for connections" address=localhost:9090
level=info ts=2018-12-17T16:50:23.774011018Z caller=main.go:564 msg="TSDB started"
level=info ts=2018-12-17T16:50:23.779929925Z caller=main.go:624 msg="Loading configuration file" filename=/opt/outline/persisted-state/prometheus/config.yml
level=debug ts=2018-12-17T16:50:23.783900529Z caller=manager.go:158 component="discovery manager scrape" msg="Starting provider" provider=string/0 subs=[outline-server-main]
level=debug ts=2018-12-17T16:50:23.783996692Z caller=manager.go:158 component="discovery manager scrape" msg="Starting provider" provider=string/1 subs=[outline-server-ss]
level=debug ts=2018-12-17T16:50:23.784874489Z caller=manager.go:158 component="discovery manager scrape" msg="Starting provider" provider=string/2 subs=[prometheus]
level=info ts=2018-12-17T16:50:23.784951697Z caller=main.go:650 msg="Completed loading of configuration file" filename=/opt/outline/persisted-state/prometheus/config.yml
level=info ts=2018-12-17T16:50:23.785502418Z caller=main.go:523 msg="Server is ready to receive web requests."
level=debug ts=2018-12-17T16:50:23.789627999Z caller=manager.go:180 component="discovery manager scrape" msg="discoverer channel closed, sending the last update" provider=string/0
level=debug ts=2018-12-17T16:50:23.789736916Z caller=manager.go:180 component="discovery manager scrape" msg="discoverer channel closed, sending the last update" provider=string/1
level=debug ts=2018-12-17T16:50:23.789809752Z caller=manager.go:180 component="discovery manager scrape" msg="discoverer channel closed, sending the last update" provider=string/2
level=debug ts=2018-12-17T16:50:23.790561124Z caller=manager.go:183 component="discovery manager scrape" msg="discoverer exited" provider=string/0
level=debug ts=2018-12-17T16:50:23.792187824Z caller=manager.go:183 component="discovery manager scrape" msg="discoverer exited" provider=string/1
level=debug ts=2018-12-17T16:50:23.792273895Z caller=manager.go:183 component="discovery manager scrape" msg="discoverer exited" provider=string/2
level=info ts=2018-12-17T16:50:23.79252571Z caller=main.go:423 msg="Stopping scrape discovery manager..."
level=info ts=2018-12-17T16:50:23.792575803Z caller=main.go:437 msg="Stopping notify discovery manager..."
level=info ts=2018-12-17T16:50:23.792626246Z caller=main.go:459 msg="Stopping scrape manager..."
level=info ts=2018-12-17T16:50:23.792698334Z caller=main.go:419 msg="Scrape discovery manager stopped"
level=info ts=2018-12-17T16:50:23.79276021Z caller=main.go:433 msg="Notify discovery manager stopped"
level=info ts=2018-12-17T16:50:23.792826785Z caller=manager.go:638 component="rule manager" msg="Stopping rule manager..."
level=info ts=2018-12-17T16:50:23.792862409Z caller=manager.go:644 component="rule manager" msg="Rule manager stopped"
level=info ts=2018-12-17T16:50:23.79304756Z caller=notifier.go:512 component=notifier msg="Stopping notification manager..."
level=info ts=2018-12-17T16:50:23.793092836Z caller=main.go:608 msg="Notifier manager stopped"
level=info ts=2018-12-17T16:50:23.793126269Z caller=main.go:453 msg="Scrape manager stopped"
level=error ts=2018-12-17T16:50:23.793160344Z caller=main.go:617 err="error starting web server: listen tcp [wrong ip]:9090: bind: cannot assign requested address"
```
That's what I got. It looks like the same thing as before.

**Comment by rtsp** [comment]
> 1. Save the environment of the running container:
> 
> ```
> sudo docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' shadowbox | grep SB_ > /opt/outline/docker.env
> ```

Interesting, this command show correct ip address of my outline server (aka. `outline.mydomain.com`) in SB_PUBLIC_IP so I did not continue further

```
SB_API_PREFIX=xxxxxxxx
SB_CERTIFICATE_FILE=/root/shadowbox/persisted-state/shadowbox-selfsigned.crt
SB_PRIVATE_KEY_FILE=/root/shadowbox/persisted-state/shadowbox-selfsigned.key
SB_METRICS_URL=
SB_DEFAULT_SERVER_NAME=
SB_STATE_DIR=/root/shadowbox/persisted-state
SB_PUBLIC_IP=103.253.x.x
SB_API_PORT=7078
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE_VERSION=8.11.3
YARN_VERSION=1.6.0
```

---


> One thing to try that may give us more information is to run prometheus manually:
> 
> ```
> sudo docker exec -it shadowbox /root/shadowbox/bin/prometheus --config.file /opt/outline/persisted-state/prometheus/config.yml --storage.tsdb.retention 31d --storage.tsdb.path /opt/outline/persisted-state/prometheus/data --web.listen-address localhost:9090 --log.level debug
> ```
> Do you get the same error?

Yes, not exactly but last line showing that it trying to bind on public IP of `mydomain.com` (not outline server `outline.mydomain.com`)

```
level=info ts=2018-12-17T16:52:08.162718151Z caller=main.go:238 msg="Starting Prometheus" version="(version=2.4.3, branch=HEAD, revision=167a4b4e73a8eca8df648d2d2043e21bdb9a7449)"
level=info ts=2018-12-17T16:52:08.162805779Z caller=main.go:239 build_context="(go=go1.11.1, user=root@1e42b46043e9, date=20181004-08:42:02)"
level=info ts=2018-12-17T16:52:08.162832708Z caller=main.go:240 host_details="(Linux 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 **** (none))"
level=info ts=2018-12-17T16:52:08.162855845Z caller=main.go:241 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2018-12-17T16:52:08.162880059Z caller=main.go:242 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2018-12-17T16:52:08.164176748Z caller=web.go:397 component=web msg="Start listening for connections" address=localhost:9090
level=info ts=2018-12-17T16:52:08.164131312Z caller=main.go:554 msg="Starting TSDB ..."
level=info ts=2018-12-17T16:52:08.230982738Z caller=main.go:423 msg="Stopping scrape discovery manager..."
level=info ts=2018-12-17T16:52:08.231048217Z caller=main.go:437 msg="Stopping notify discovery manager..."
level=info ts=2018-12-17T16:52:08.231063235Z caller=main.go:459 msg="Stopping scrape manager..."
level=info ts=2018-12-17T16:52:08.231077267Z caller=main.go:433 msg="Notify discovery manager stopped"
level=info ts=2018-12-17T16:52:08.231111626Z caller=main.go:453 msg="Scrape manager stopped"
level=info ts=2018-12-17T16:52:08.231134899Z caller=main.go:419 msg="Scrape discovery manager stopped"
level=info ts=2018-12-17T16:52:08.231161854Z caller=manager.go:638 component="rule manager" msg="Stopping rule manager..."
level=info ts=2018-12-17T16:52:08.231220723Z caller=manager.go:644 component="rule manager" msg="Rule manager stopped"
level=info ts=2018-12-17T16:52:08.231287267Z caller=notifier.go:512 component=notifier msg="Stopping notification manager..."
level=info ts=2018-12-17T16:52:08.231364867Z caller=main.go:608 msg="Notifier manager stopped"
level=info ts=2018-12-17T16:52:08.240720756Z caller=main.go:564 msg="TSDB started"
level=error ts=2018-12-17T16:52:08.240762788Z caller=main.go:617 err="error starting web server: listen tcp 103.253.x.x:9090: bind: cannot assign requested address" <-- wrong ip (ip of my root domain instead of subdomain)
```

**Comment by MaybeGoogle** [comment]
> @ rtsp it possible, but a bit involved:
> 
> 1. Save the environment of the running container:
> 
> ```
> sudo docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' shadowbox | grep SB_ > /opt/outline/docker.env
> ```
> 1. Edit `SB_PUBLIC_IP` on `docker.env`

I'm getting the correct IP for `SB_PUBLIC_IP` here

**Comment by fortuna** [comment]
Thanks for all the feedback. It seems based on @rtsp 's logs that the problem is indeed with prometheus.

@rtsp, if you are inclined to try, do you still get the same issue if you run outside Docker? You can download Prometheus from here: https://prometheus.io/download/

The version in the image is v2.4.3:
https://github.com/prometheus/prometheus/releases/tag/v2.4.3

Thanks a lot, and I'm sorry again for the trouble!

**Comment by fortuna** [comment]
Another question to all: do you see the bogus IP when you run `ifconfig`?

**Comment by MaybeGoogle** [comment]
nope, ifconfig looks fine. Thanks for taking your time to help!

**Comment by rtsp** [comment]
I've found some clue. If I run prometheus manually and specify argument to listen on `127.0.0.1:9090` instead of `localhost:9090` it will able to run pass that point.

This problem occured only inside container `shadowbox`. If I run promethus manually outside docker using `localhost:9090` everything is fine.

```
sudo docker exec -it shadowbox /root/shadowbox/bin/prometheus --config.file /opt/outline/persisted-state/prometheus/config.yml --storage.tsdb.retention 31d --storage.tsdb.path /opt/outline/persisted-state/prometheus/data --web.listen-address 127.0.0.1:9090 --log.level debug
```
---

Looks like there's some problem with docker image that resolving `localhost` return an IP address of a root domain of this server instead of 127.0.0.1

```
~/shadowbox # cat /etc/hosts
127.0.0.1 localhost
::1 ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

~/shadowbox # nslookup localhost
nslookup: can't resolve '(null)': Name does not resolve

Name:      localhost
Address 1: 127.0.0.1 localhost

~/shadowbox # ping localhost
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.098 ms
```

I tried to resolve `localhost` in docker using every command I know all of them return `127.0.0.1` (as shown above). I also `grep -r 103.253.x.x /` (the wrong ip) inside docker container and there's nothing in return.

**Comment by fortuna** [comment]
@rtsp What about your /etc/resolv.conf? is there anything suspicious there?

I'm trying to search for the problem, but it's hard to find something relevant. I found this case:
https://askubuntu.com/questions/646345/localhost-is-wrong-ip-address
Where the person claims the system was doing other forms of IP resolution. Your host system may have something that is influencing the localhost resolution.

**Comment by rtsp** [comment]
@fortuna everything looks fine from here. no `domain` or `search` line specified in /etc/resolv.conf, only 2 lines of google dns server.

```
~/shadowbox # nslookup localhost 8.8.8.8
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com

Name:      localhost
Address 1: 127.0.0.1 localhost

~/shadowbox # cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Comment by fortuna** [comment]
This is quite hard for us to debug, since we can't reproduce it and I wasn't able to find much information on the internet.

However, I have a change that should fix the problem. I'll use the 127.0.0.1 IP address rather than `localhost` for prometheus. See https://github.com/Jigsaw-Code/outline-server/pull/359/commits/73fff76637edb52230ce4384be03315463e2ab04

**Comment by fortuna** [comment]
@rtsp Here is another way to check the localhost resolution: `getent ahosts localhost`
Could you try that?

**Comment by rtsp** [comment]
@fortuna still no luck

```
~/shadowbox # getent hosts localhost
127.0.0.1         localhost  localhost
~/shadowbox # getent ahosts localhost
127.0.0.1       STREAM localhost
127.0.0.1       DGRAM  localhost
~/shadowbox # getent ahostsv4 localhost
127.0.0.1       STREAM localhost
127.0.0.1       DGRAM  localhost
```

I'm going to reinstall this server next week so the problem may gone and i can not test anything further. Let me know if there's anything I can help testing for now.

**Comment by fortuna** [comment]
The fix will be released soon.
